version: '3.3'

services:
  api:
    container_name: corda
    #    image: cordatest.azurecr.io/cordatest-api:dev
    build:
      dockerfile: docker/api.dockerfile
    ports:
      - 61000:61000
    depends_on:
      - corda
    links:
      - corda:corda
    mem_limit: 4096m

# may use h2
  corda:
    container_name: corda
#    image: cordatest.azurecr.io/cordatest-corda:dev
    build:
      dockerfile: docker/corda.dockerfile
    environment:
      DB_HOST: db
    depends_on:
      - db
    links:
      - db:db
    mem_limit: 4096m

  db:
    container_name: db
#    image: cordatest.azurecr.io/cordatest-db:dev
    build:
      dockerfile: docker/db.dockerfile
    environment:
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432
    mem_limit: 300m
